spring:
  #Defaulted to h2, expected is postgres configuration while running on servers
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: true

server:
  port: 9651

logging:
  level:
    ROOT: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
      base-path: /appinfo/actuator
